apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enrollment-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-db
  template:
    metadata:
      labels:
        app: enrollment-db
    spec:
      containers:
        - name: enrollment-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: enrollments

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: enrollment-db-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d enrollments
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d enrollments
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

      volumes:
        - name: enrollment-db-storage
          persistentVolumeClaim:
            claimName: enrollment-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-db
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: enrollment-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432