apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      initContainers:
        - name: wait-for-user-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready \
                -h user-db \
                -p 5432 \
                -U postgres \
                -d users;
              do
                echo "Waiting for user database..."
                sleep 3
              done

      containers:
        - name: user-service
          image: koalatech-user-service:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: koalatech-application-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koalatech-application-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: users

            - name: POSTGRES_HOST
              value: user-db

            - name: POSTGRES_PORT
              value: "5432"

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: koalatech-application-secret
                  key: JWT_SECRET_KEY

            - name: JWT_ALGORITHM
              value: HS256

            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"

            - name: DEFAULT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: koalatech-application-secret
                  key: DEFAULT_ADMIN_USERNAME

            - name: DEFAULT_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: koalatech-application-secret
                  key: DEFAULT_ADMIN_EMAIL

            - name: DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: koalatech-application-secret
                  key: DEFAULT_ADMIN_PASSWORD

          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  type: ClusterIP

  selector:
    app: user-service

  ports:
    - name: http
      port: 8000
      targetPort: 8000